# 아이템 8. finalizer와 cleaner 사용을 피하라

```java
public class Finalizable {

	private BufferedReader reader;

	public Finalizable() {
		InputStream input = this.getClass()
				.getClassLoader()
				.getResourceAsStream("file.txt");

		this.reader = new BufferedReader(new InputStreamReader(input));
	}

	public String readFirstLine() throws IOException {
		return reader.readLine();
	}

	@Override
	public void finalize() {
		try {
			reader.close();
			System.out.println("Closed BufferedReader in the finalizer");
		} catch (IOException e) {
			// ...
		}
	}

	public static void main(String[] args) throws IOException {
		String firstLine = new Finalizable().readFirstLine();

		if (!"effective java".equals(firstLine)) {
			throw new AssertionError("Expected 'effective java' but was '" + firstLine + "'");
		}

		System.out.println("Test passed successfully");
		System.gc();
	}
}
```

* Finalizer란, Object에 존재하는 `finalize()`를 말한다. 클래스의 객체가 더 이상 사용되지 않으면 GC가 자동으로 호출된다.
* Cleaner란, Java 9에서 새로 생긴 개념으로 별도의 쓰레드를 사용해서 finalizer보다는 덜 위험하지만, 여전히 예측 불가하고 느리고 불필요하다. 


### finalizer와 cleaner 문제점

* 성능 저하
  * `try-with-resources`를 사용하기 위해 AutoCloseable 인터페이스를 구현하는 방식보다 성능이 좋지 않다.
  * GC의 효율성을 떨어뜨린다.
* 실행이 안 될 가능성
  * finalizer나 cleaner는 수행 시점 예측이 어렵고 수행 여부 또한 확실하게 보장할 수 없다.
  * System.gc()나 System.runFinalization() 메서드가 finalizer와 cleaner 실행 가능성을 높여줄 수 있으나 역시 보장해주진 않는다.
* 예외 발생 무시
  * finalizer 동작 중 처리할 작업이 남았더라도 그 순간 종료된다.
  * 마무리가 덜 된 상태의 객체가 힙 영역에 남아 있어 다른 쓰레드가 이 훼손된 객체를 사용하게 되면 어떻게 동작할지 예측할 수 없다.
* 인스턴스 반납 지연
  * finalizer 쓰레드의 경우 다른 애플리케이션 쓰레드보다 우선순위가 낮아 실행될 기회를 제대로 얻지 못하는 경우가 많다.
  * 어떤 쓰레드에 의해 finalizer를 수행할지 모르기 때문에 사용하지 않는 것이 좋다.
* 보안 문제
  * finalizer를 사용한 클래스에서 생성자나 직렬화 과정 시 예외가 발생하면 생성되다 만 객체에서 악의적인 하위 클래스의 finalizer가 수행될 수 있게 한다.
  * 그렇게 되면 이 finalizer는 자신의 참조를 할당하여 다 쓴 객체(참조가 없는 객체)로 인식하지 못하게 하면서 GC의 대상이 되지 못하도록 막는다.

### AutoCloseable 인터페이스를 구현하고 try-with-resources를 사용하라.

* 클라이언트에서 인스턴스를 다 쓰고 나면 자동적으로 호출해주는 `close()`를 사용하면 예외가 발생해도 제대로 자원을 반납할 수 있게 된다.

```java
public class Resource implements AutoCloseable {

	private InputStream inputStream;

	public Resource() throws FileNotFoundException {
		this.inputStream = new FileInputStream("example.txt");
	}

	public void method() {
		System.out.println("자원 사용 중...");
	}

	@Override
	public void close() {
		if (inputStream != null) {
			inputStream.close();
			System.out.println("자원 반납 확인");
		}
	}
}
```

```java
public class ResourceMain {

	public static void main(String[] args) throws FileNotFoundException {

		try (Resource resource = new Resource()) {
			resource.method();
			throw new RuntimeException("고의로 예외 터뜨리기");
		} catch (FileNotFoundException e) {
			e.printStackTrace();
		}
	}
}
```

> 실행 결과

```text
자원 사용 중...
자원 반납 확인
Exception in thread "main" java.lang.RuntimeException: 고의로 예외 터뜨리기
	at ResourceMain.main(ResourceMain.java:9)
```

* FileNotFoundException의 부모는 IOException, 그리고 이 상위의 예외는 Exception이다.
* try 블록에서 고의로 언체크 예외를 터뜨려도 입력 스트림을 닫고 안전하게 자원을 반납하는 모습을 실행 결과로 확인할 수 있다.