# 아이템 9. try-finally보다는 try-with-resources를 사용하라

* 애플리케이션에서 외부 자원을 사용하는 경우 반드시 외부 자원을 해제해야 한다.
* 따라서 `finally` 구문을 반드시 사용해야 한다.
* `try`에서 외부 자원을 사용하고 `try`가 끝나면 외부 자원을 반납하는 패턴이 반복되면서 자바에서는 try-with-resources 기능을 자바 7에서 도입했다.
* 이 기능을 사용하려면 `AutoCloseable` 인터페이스를 구현해야 한다.
* `AutoCloseable` 인터페이스를 구현하면 try-with-resources를 사용할 때 try가 끝나는 시점에 `close()`가 자동으로 호출된다.

```java
public class FileOutputStream implements AutoCloseable {    // AutoCloseable 인터페이스 구현

	// close() 메서드 재정의
	@Override
	public void close() {
		System.out.println("close() 메서드 호출");
	}

	public void write(String input, boolean throwException) throws IOException {
		System.out.println("... : " + input);
		if (throwException) {
			throw new IOException("예외 발생");
		}
	}
}
```

> 실행 결과

```text
... : test
close() 메서드 호출  // 이 부분 중요!
Exception in thread "main" java.io.IOException: 예외 발생
	at FileOutputStream.write(FileOutputStream.java:13)
	at Main.method2(Main.java:20)
	at Main.main(Main.java:7)
```

* try-with-resources를 사용함으로써 코드 가독성(짧고 읽기 수월)이 좋아지면서 문제 진단 역시 수월해진다.
* 또한 아래와 같이 try-with-resources와 함께 catch문도 사용할 수 있다.

```java
public class Main {
	public static void main(String[] args) throws IOException {

		//method1("test");
		method2("test");
	}

	public static void method1(String input) throws IOException {
		try (FileOutputStream fileOutputStream = new FileOutputStream()) {
			fileOutputStream.write(input, true);
		}
	}

	public static void method2(String input) throws IOException {
        try (FileOutputStream fileOutputStream1 = new FileOutputStream()) {
			FileOutputStream fileOutputStream2 = new FileOutputStream();

			fileOutputStream1.write(input, true);
			fileOutputStream2.write(input, true);
        } catch (IOException e) {
			System.out.println("예외 잡아봅니다.");
		}
    }
}
```

> 실행 결과

```text
... : test
close() 메서드 호출
예외 잡아봅니다. // catch문으로 예외 잡기
```